title: Welcome to my Page
author: rmhm18
email: your-email@domain.com
description: 
This is website is a way to improve my skills with github. The main goal is to created somethinng special for our users.
theme: minima
twitter_username: rmhm18
github_username:  rmhm18
show_excerpts: true 
